### ISSUE TITLE
count_hit can crash in some cases

### ISSUE THREAD

**Issue by dmt** [ExHammer/hammer-backend-redis#11] opened 2018-03-01 11:05 UTC
We sporadically see this in the logs: 

```
GenServer Hammer.Backend.Redis terminating ** (MatchError) no match of right hand side value: {:ok, ["OK", "QUEUED", "QUEUED", "QUEUED", "QUEUED", ["OK", 0, 1, 1]]}
     (hammer_backend_redis) lib/hammer_backend_redis.ex:106: Hammer.Backend.Redis.handle_call/3
     (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
     (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 Last message (from #PID<0.9173.0>): {:count_hit, {1519900129, "..."}, 1519900129079}
```

Not sure why the SADD  key already exists.

**Comment by mpinkston** [comment] 2018-04-13 08:52
@dmt are you running on multiple nodes? Perhaps there's a race condition here where two nodes call handle_call at the same time after the previous bucket has expired. Since the new key doesn't yet exist, they both try to add it to the bucket.
`Redix.command(r, ["EXISTS", redis_key])` Isn't part of any transaction, so both could enter this block at the same time..
https://github.com/ExHammer/hammer-backend-redis/blob/40bb71515f35698bd821e3410bb1a14c3d52c51a/lib/hammer_backend_redis.ex#L99

A side-effect of this would be one extra call (per competitor) to HMSET as well, which would keep the counter at "1" and technically exceed the limit.

**Comment by dmt** [comment] 2018-04-16 08:58
Yes, there are 4 nodes using this.

**Comment by dmt** [comment] 2018-04-17 14:27
Would it be possible to `WATCH` the key and potentially retry the block?

**Comment by mpinkston** [comment] 2018-04-18 01:50
That's what I'm thinking. I'll see if I can find time to get a PR written

**Comment by mpinkston** [comment] 2018-04-18 06:52
I've created a PR to handle this scenario in #12

**Comment by dmt** [comment] 2018-04-18 08:11
Thanks!

**Comment by ShaneKilkelly** [comment] 2018-04-23 20:01
Sorry for the delay, I'm just seeing this now because my github notifications were misconfigured. I'll look at the PR ASAP.

**Comment by ShaneKilkelly** [comment] 2018-04-24 18:27
Fixed in version `4.0.1`

**Comment by jonzlin95** [comment] 2018-04-25 11:01
Still running into this issue w/ Version 4.0.1 (albeit less frequently).

```
Erlang error: {{{{:case_clause, {:ok, ["OK", "QUEUED", "QUEUED", "QUEUED", "QUEUED", ["OK", 0, 1, 1]]}}, [{Hammer.Backend.Redis, :create_bucket, 5, [file: 'lib/hammer_backend_redis.ex', line: 215]}, {Hammer.Backend.Redis, :handle_call, 3, [file: 'lib/hammer_backend_redis.ex', line: 108]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 636]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 665]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {GenServer, :call, [#PID<0.13085.2>, {:count_hit, {138604888, "la2-summoner"}, 1524653769748}, 5000]}}}
```

**Comment by ShaneKilkelly** [comment] 2018-04-25 12:08
@jonzlin95 just to check, you've upgraded to `hammer = 4.0.0` and `hammer_backend_redis = 4.0.1`?

**Comment by ShaneKilkelly** [comment] 2018-04-25 12:11
Also, we should maybe prioritize setting up a minimal project that can reproduce the issue, with the help of a load-tester like [artillery](https://artillery.io/).

Some details on the kind of cluster setups that are experiencing this problem could be a good place to start :)

**Comment by ShaneKilkelly** [comment] 2018-04-25 12:12
I can also start by adding transactions where we don't have any yet, will take a look at that in the next few days.

**Comment by jonzlin95** [comment] 2018-04-25 12:17
I believe so, I just re-deployed my app to make sure. Our peak usage hours are ~1pm PST, so will report back later today.

**Comment by ShaneKilkelly** [comment] 2018-04-25 12:24
Cool, do you have a sense for how often this happens? Like a ratio of successful requests to these failures? Also, how many machines are your services spread out on?

**Comment by jonzlin95** [comment] 2018-04-25 12:28
Spread out on 13 machines, I have a pretty small window (10 seconds for 500/1000 requests depending on the endpoint). Unsure as to the hit/miss rate (I use honeybadger which only tells me on errors), but it's currently averaging ~1/minute. 

Unfortunately, I'm likely going to have to swap back to limiting the rate limiter to a single instance for the day, to avoid the failed requests, but happy to provide other information if needed!

**Comment by ShaneKilkelly** [comment] 2018-04-25 12:30
Thanks for the details!

I'll try the following:

- Add transactions to all redis pipelines
- Set up a demo app to replicate the problem

**Comment by ShaneKilkelly** [comment] 2018-04-25 12:31
Oh, one more question, is your system using Erlang clustering, or load-balancing between separate instances (more like a traditional web-app)?

**Comment by jonzlin95** [comment] 2018-04-25 12:31
Erlang clustering w/ libcluster

**Comment by ShaneKilkelly** [comment] 2018-04-26 21:56
Ok, I can recreate the issue. I set up project [here](https://github.com/ShaneKilkelly/hammer_load_test) to load-test a set of phoenix servers using [artillery](https://artillery.io).

The result is that I see a couple of requsts failing with the error described above. Now that we have a test-case, we have something to use to check when we've squashed the bug.

**Comment by ShaneKilkelly** [comment] 2018-04-27 13:54
Ok, I think I've fixed it. The fix is in `4.0.2`

**Comment by jonzlin95** [comment] 2018-04-28 23:54
I will deploy with v 4.0.2 later tonight. My app is ~120 req/s on rate limited endpoints (but it's bursty), and will report back w/ findings tomorrow.

Thanks!

**Comment by jonzlin95** [comment] 2018-04-30 21:30
Success! The bug has been killed, thanks @ShaneKilkelly for being so quick to fix it, huge props to you. 

There is a new bug, (had only 1 hit last hour, so a lot less frequent), but here's the stacktrace for it

```
Full Backtrace
Failed to count hit: too many attempts to create bucket.
hammer_backend_redis.ex  160 do_count_hit/5
lib/hammer_backend_redis.ex:160:in `do_count_hit/5'
hammer_backend_redis.ex  108 handle_call/3
lib/hammer_backend_redis.ex:108:in `handle_call/3'
gen_server.erl  636 try_handle_call/4
gen_server.erl:636:in `try_handle_call/4'
gen_server.erl  665 handle_msg/6
gen_server.erl:665:in `handle_msg/6'
proc_lib.erl  247 init_p_do_apply/3
proc_lib.erl:247:in `init_p_do_apply/3'
```

**Comment by ShaneKilkelly** [comment] 2018-05-01 08:03
Glad to hear the main bug is squashed!

That error seems to be from https://github.com/ExHammer/hammer-backend-redis/blob/master/lib/hammer_backend_redis.ex#L162, where we retry the bucket creation twice before giving up.

I'll take a look this evening. But I suspect we could either increase the number of attempts before giving up, or figure out another way of handling that case.

**Comment by ShaneKilkelly** [comment] 2018-05-01 17:02
@jonzlin95 I've published version `4.0.3-rc1` with a speculative fix for the `too many attempts to create bucket` issue. Would you mind giving it a try?

**Comment by jonzlin95** [comment] 2018-05-07 20:51
Seems solved to me @ShaneKilkelly

**Comment by ShaneKilkelly** [comment] 2018-05-08 08:13
Excellent, I'll push out a proper release of `4.0.3`, thanks for the great teamwork everyone!

**Closed** 2018-05-08 08:17 UTC
Labels: bug
